# Machine Learning Based Recommendation Systems
## Content-Based Recommender Systems
## Nearest Neighbors Algorithm(unsupervise)
### find something similar example

In [1]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.neighbors import NearestNeighbors

*mtcars dataset source:* 
Henderson and Velleman (1981), Building multiple regression models interactively. Biometrics, 37, 391–411.

In [2]:
cars = pd.read_csv('mtcars.csv')
cars.columns = ['car_names', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']
cars.head()

car_names   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [16]:
#select features: mpg,disp,hp,wt 
X = cars.iloc[:,[1, 3, 4, 6]].values
X[0:5]

array([[  21.   ,  160.   ,  110.   ,    2.62 ],
       [  21.   ,  160.   ,  110.   ,    2.875],
       [  22.8  ,  108.   ,   93.   ,    2.32 ],
       [  21.4  ,  258.   ,  110.   ,    3.215],
       [  18.7  ,  360.   ,  175.   ,    3.44 ]])

In [10]:
# setup NearestNeighbors values
# mpg,disp,hp,wt
t = [15, 300, 160, 3.2]
t

[15, 300, 160, 3.2]

# Import Predictor

In [11]:
# Train model to get 1 most nearest neigbor
nnb = NearestNeighbors(n_neighbors=1)
nbrs = nnb.fit(X)

In [12]:
# Calculate most nearest to t[]
print(nbrs.kneighbors([t]))

(array([[ 10.77474942]]), array([[22]], dtype=int64))


In [22]:
cars.iloc[22]

car_names    AMC Javelin
mpg                 15.2
cyl                    8
disp                 304
hp                   150
drat                3.15
wt                 3.435
qsec                17.3
vs                     0
am                     0
gear                   3
carb                   2
Name: 22, dtype: object

In [17]:
# Get 2 items (first and second) most nearest neigbor
nbrs = NearestNeighbors(n_neighbors=2).fit(X)
print(nbrs.kneighbors([t]))

(array([[ 10.77474942,  20.59981553]]), array([[22, 21]], dtype=int64))


In [23]:
cars.iloc[22]

car_names    AMC Javelin
mpg                 15.2
cyl                    8
disp                 304
hp                   150
drat                3.15
wt                 3.435
qsec                17.3
vs                     0
am                     0
gear                   3
carb                   2
Name: 22, dtype: object

In [24]:
cars.iloc[21]

car_names    Dodge Challenger
mpg                      15.5
cyl                         8
disp                      318
hp                        150
drat                     2.76
wt                       3.52
qsec                    16.87
vs                          0
am                          0
gear                        3
carb                        2
Name: 21, dtype: object