# Numpy Basics

# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [3]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [4]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [10]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [11]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [12]:
np.ones(3)

array([ 1.,  1.,  1.])

In [13]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [14]:
np.linspace(0,10,3)

array([  0.,   5.,  10.])

In [15]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

## eye

Creates an identity matrix

In [16]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [17]:
np.random.rand(2)

array([ 0.50836533,  0.17758201])

In [18]:
np.random.rand(5,5)

array([[ 0.61849264,  0.6465045 ,  0.11072624,  0.9769721 ,  0.29199651],
       [ 0.28900093,  0.6855851 ,  0.28397492,  0.95511635,  0.83192911],
       [ 0.98078399,  0.52290851,  0.43942539,  0.91867839,  0.27392515],
       [ 0.44868257,  0.52101906,  0.68270288,  0.12275061,  0.70449936],
       [ 0.04458857,  0.67014167,  0.52378885,  0.59350182,  0.94567783]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [20]:
np.random.randn(2)

array([ 0.58218697, -0.27760542])

In [21]:
np.random.randn(5,5)

array([[-1.23148711,  0.32608374,  0.64420348,  0.57208437,  0.21804371],
       [ 1.25117675,  1.62380533,  0.71024138,  0.60726664, -1.00767325],
       [-0.44907257,  0.23192967, -0.48349549, -0.98538877,  1.05459127],
       [-0.22508567, -0.97573445, -0.92536279,  1.06451878,  0.39797291],
       [-0.56744307,  0.91374408, -0.7673137 , -0.14034007, -1.5096266 ]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [22]:
np.random.randint(1,100)

44

In [23]:
np.random.randint(1,100,10)

array([25, 95,  2, 28, 73, 11, 73, 46, 79, 79])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [26]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr

array([48, 41, 49, 38, 22, 26, 18, 12, 42, 48])

## Reshape
Returns an array containing the same data with a new shape.

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [30]:
ranarr

array([48, 41, 49, 38, 22, 26, 18, 12, 42, 48])

In [31]:
ranarr.max()

49

In [32]:
ranarr.argmax()

2

In [33]:
ranarr.min()

12

In [34]:
ranarr.argmin()

7

## Shape

Shape is an attribute that arrays have (not a method):

In [35]:
# Vector
arr.shape

(25,)

In [36]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [37]:
arr.reshape(1,25).shape

(1, 25)

In [38]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [39]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [40]:
arr.dtype

dtype('int64')

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [41]:
import numpy as np

In [42]:
#Creating sample array
arr = np.arange(0,11)

In [43]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [44]:
#Get a value at an index
arr[8]

8

In [45]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [46]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [47]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [48]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [50]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [51]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [52]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [53]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [54]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [55]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [56]:
# Getting individual element value
arr_2d[1,0]

20

In [57]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [58]:
arr_2d[:1,2:]

array([[15]])

In [59]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [60]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [61]:
#Set up matrix
arr2d = np.zeros((10,10))

In [62]:
#Length of array
arr_length = arr2d.shape[1]

In [64]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

Fancy indexing allows the following

In [65]:
arr2d[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

In [66]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to fins useful images, like this one:

<img src= 'http://memory.osu.edu/classes/python/_images/numpy_indexing.png' width=500/>

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [67]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [69]:
bool_arr = arr>4

In [70]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [71]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [72]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
arr = np.arange(3)

In [106]:
arr[np.array([True, False, True])]

array([0, 2])

In [107]:
arr >= 1

array([False,  True,  True], dtype=bool)

In [108]:
arr[arr>=1]

array([1, 2])

In [109]:
arr = np.arange(10)

In [110]:
arr[(arr>2)&(arr<7)]

array([3, 4, 5, 6])

In [111]:
arr[(arr>7)|(arr<2)]

array([0, 1, 8, 9])

In [112]:
arr[~(arr>7)]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [113]:
mat = np.random.rand(5, 5)
mat

array([[ 0.80124133,  0.62906   ,  0.3819804 ,  0.11297617,  0.78772561],
       [ 0.54483777,  0.07882115,  0.64779205,  0.70698356,  0.42857978],
       [ 0.06035209,  0.1114194 ,  0.60805948,  0.20381787,  0.50329167],
       [ 0.97092121,  0.17611903,  0.0399887 ,  0.5650425 ,  0.51226776],
       [ 0.4086292 ,  0.09244622,  0.47334416,  0.22424512,  0.94127471]])

In [114]:
mat[np.abs(mat - mat.mean()) > 1.5*mat.std()]

array([ 0.97092121,  0.94127471])

In [115]:
np.abs(mat - mat.mean())

array([[ 0.36079266,  0.18861132,  0.05846828,  0.32747251,  0.34727693],
       [ 0.10438909,  0.36162753,  0.20734337,  0.26653489,  0.0118689 ],
       [ 0.38009658,  0.32902928,  0.1676108 ,  0.2366308 ,  0.06284299],
       [ 0.53047254,  0.26432965,  0.40045998,  0.12459382,  0.07181908],
       [ 0.03181947,  0.34800246,  0.03289548,  0.21620356,  0.50082603]])

In [116]:
np.abs(mat - mat.mean()) > 1.5*mat.std()

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False,  True]], dtype=bool)

In [117]:
mat[np.abs(mat - mat.mean()) > 1.5*mat.std()]

array([ 0.97092121,  0.94127471])

In [119]:
mat[np.abs(mat - mat.mean()) > 1.5*mat.std()] = mat.mean()

## Slicing

In [86]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [87]:
len(arr)

3

In [88]:
arr[1]

2

In [89]:
type(arr[1])

numpy.int64

In [90]:
arr.dtype

dtype('int64')

In [91]:
arr32 = np.array([1,2,3], dtype=np.int32)
arr32

array([1, 2, 3], dtype=int32)

In [92]:
arr * arr

array([1, 4, 9])

In [93]:
v1 = np.random.rand(1000000)
v2 = np.random.rand(1000000)

In [94]:
%time v1 * v2

CPU times: user 2.97 ms, sys: 3.85 ms, total: 6.82 ms
Wall time: 5.74 ms


array([ 0.40571903,  0.04090955,  0.27855868, ...,  0.39255143,
        0.17432777,  0.19265517])

In [95]:
np.dot(arr, arr)

14

In [96]:
arr @ arr

14

In [97]:
mat = np.array([[1,2,3], [4,5,6], [7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
v = np.arange(12)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [99]:
v.reshape((4, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [100]:
mat = np.arange(12).reshape((4, 3))
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [101]:
mat.shape

(4, 3)

In [102]:
mat2 = mat.reshape((3, 4))
mat2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
mat[1,2] = 17

In [104]:
mat2

array([[ 0,  1,  2,  3],
       [ 4, 17,  6,  7],
       [ 8,  9, 10, 11]])

# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [74]:
import numpy as np
arr = np.arange(0,10)

In [75]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [76]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [77]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [78]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

/Users/smarthome/anaconda/envs/techtalent/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [79]:
# Also warning, but not an error instead infinity
1/arr

/Users/smarthome/anaconda/envs/techtalent/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111])

In [80]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [120]:
mat = np.arange(9).reshape((3, 3))
vec = np.arange(3)

In [121]:
mat + vec

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [122]:
v1 = np.arange(3)
v2 = np.arange(3).reshape((3, 1))

In [123]:
v2

array([[0],
       [1],
       [2]])

In [124]:
v2.shape

(3, 1)

In [125]:
v1 + v2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [129]:
 v = np.arange(12).reshape((4, 3))

In [130]:
dir(v)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_e

In [131]:
v.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [132]:
v.any()

True

In [133]:
v.all()

False

In [135]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [136]:
v.prod()

0

In [137]:
v.sum(axis=1)

array([ 3, 12, 21, 30])

In [138]:
v.sum(axis=0)

array([18, 22, 26])

In [139]:
v1 = v.copy()

In [140]:
v1[0,0] = 1000
v

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [141]:
data = v.dumps()
data

b'\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x04K\x03\x86q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00i8q\x0cK\x00K\x01\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00<q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x10b\x89h\x03X`\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x07\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\t\x00\x00\x00\x00\x00\x00\x00\n\x00\x00\x00\x00\x00\x00\x00\x0b\x00\x00\x00\x00\x00\x00\x00q\x11h\x05\x86q\x12Rq\x13tq\x14b.'

In [142]:
v2 = np.loads(data)
v2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [81]:
#Taking Square Roots
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [82]:
#Calcualting exponential (e^)
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [83]:
np.max(arr) #same as arr.max()

9

In [84]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [85]:
np.log(arr)

/Users/smarthome/anaconda/envs/techtalent/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458])

## Understand ufunc

In [143]:
np.sin(np.pi/2)

1.0

In [144]:
v = np.arange(-3, 3)
np.sin(v)

array([-0.14112001, -0.90929743, -0.84147098,  0.        ,  0.84147098,
        0.90929743])

In [145]:
def noneg(n):
    if n < 0:
        return 0
    return n

In [146]:
noneg(7)

7

In [147]:
noneg(-3)

0

In [150]:
noneg(v)

TypeError: '<' not supported between instances of 'builtin_function_or_method' and 'int'

In [151]:
@np.vectorize
def noneg(n):
    if n < 0:
        return 0
    return n

In [152]:
def noneg(n):
    if n < 0:
        return 0
    return n
noneg = np.vectorize(noneg)

In [153]:
noneg(3)

array(3)

In [154]:
noneg(3).shape

()

In [155]:
noneg(v)

array([0, 0, 0, 0, 1, 2])

In [156]:
nv = np.array([-1, np.nan, 1])
np.sin(nv)

array([-0.84147098,         nan,  0.84147098])

In [157]:
noneg(nv)

ValueError: cannot convert float NaN to integer

In [159]:
@np.vectorize
def noneg(n):
    if not np.isnan(n) and n < 0:
        return n.__class__(0)
    return n

In [160]:
noneg(nv)

array([  0.,  nan,   1.])

In [161]:
@np.vectorize
def isneg(n):
    return not np.isnan(n) and n < 0

In [162]:
nv[isneg(nv)] = 0

In [163]:
nv

array([  0.,  nan,   1.])