# Machine Learning Pretest
## First Part: Multiple Choices
## https://goo.gl/forms/L3L2RH9NMQtGPe4I2

## Second Part: Coding Exercise

## Exercise 1
### Simulate N coin flips and count number of head and number of tail

In [111]:
import numpy as np
from numpy.random import *

In [112]:
def simulate_coin_flips(N, p):
    head = 0
    tail = 0
    for i in random(N):
        if i < p:
            head += 1
        else:
            tail += 1
    return (head, tail)
    """
    return (number of head, number of tail)
    """

## Exercise 2
### Write a program to simulate data and answer this question: How many coin flips on average does it take to get n consecutive heads?

In [114]:
def average_coin_flips_until_n_heads(n, p):
    head = 0
    tail = 0
    count = 0
    while True:
        if head == n:
            break
        if random() < p:
            head += 1
        else:
            head = 0
        count += 1
    return count
    """
    return the answer
    """

## Exercise 3
### Fit linear regression on the simulated data below and show that the fitted parameters are correct

In [1]:
import numpy as np

x = np.random.normal(size=(100,2))
y = 4 + 3 * x[:,0] + 5 * x[:,1]

100

In [21]:
a = np.array([[1,2],[3,4]])
b=np.array([[4,5],[6,7]])

In [40]:
(1/(2*x.shape[0])*(x.dot(theta)-y)**2)

array([[ 0.03765226,  0.30819739,  0.76916299, ...,  0.13035196,
         0.03178402,  0.02534828],
       [ 0.03765226,  0.30819739,  0.76916299, ...,  0.13035196,
         0.03178402,  0.02534828],
       [ 0.03765226,  0.30819739,  0.76916299, ...,  0.13035196,
         0.03178402,  0.02534828],
       ..., 
       [ 0.03765226,  0.30819739,  0.76916299, ...,  0.13035196,
         0.03178402,  0.02534828],
       [ 0.03765226,  0.30819739,  0.76916299, ...,  0.13035196,
         0.03178402,  0.02534828],
       [ 0.03765226,  0.30819739,  0.76916299, ...,  0.13035196,
         0.03178402,  0.02534828]])

In [5]:
theta = np.array([[0],[0]])
y = theta[0] + x*theta[1]


array([[0],
       [0]])

In [60]:
"""
YOUR CODE HERE
"""
from sklearn.linear_model import LinearRegression
model1 = LinearRegression()
model1.fit(x,y)
print('Coef:', model1.coef_,'\nIntercept:',model1.intercept_)

Coef: [ 3.  5.] 
Intercept: 4.0


## Exercise 4
### Given credit card fraud data below, fit a classification model on the trainData and evaluate the model on the testData using Area under curve of ROC (AUC) as a metric
### The label column is "Class" and other columns are anonymized features
### The data is sample from this dataset: https://www.kaggle.com/dalpozz/creditcardfraud

In [10]:
import pandas as pd

In [15]:
trainData = pd.read_csv("trainData.csv")

In [16]:
testData = pd.read_csv("testData.csv")

In [43]:
"""
YOUR CODE HERE
"""
from sklearn.linear_model import LogisticRegression
model2 = LogisticRegression()
model2.fit(trainData.iloc[:,:-1],trainData['Class'])
prediction = model2.predict(testData.iloc[:,:-1])

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [48]:
from sklearn import metrics

In [49]:
metrics.roc_curve(testData['Class'],prediction)

(array([ 0.   ,  0.005,  1.   ]),
 array([ 0.  ,  0.86,  1.  ]),
 array([2, 1, 0]))

In [50]:
metrics.roc_auc_score(testData['Class'],prediction)

0.92749999999999988